// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: messages-xsy.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//*
// request: add slave admin request
// send message to master
type XSYAddAdminReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"` //slave address
	Amount  *uint32 `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
}

func (x *XSYAddAdminReq) Reset() {
	*x = XSYAddAdminReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddAdminReq) ProtoMessage() {}

func (x *XSYAddAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddAdminReq.ProtoReflect.Descriptor instead.
func (*XSYAddAdminReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{0}
}

func (x *XSYAddAdminReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYAddAdminReq) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

//*
// response: add slave admincd
type XSYSignRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`     //slave address
	Signature []byte  `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"` // signature of the message
}

func (x *XSYSignRsp) Reset() {
	*x = XSYSignRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYSignRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYSignRsp) ProtoMessage() {}

func (x *XSYSignRsp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYSignRsp.ProtoReflect.Descriptor instead.
func (*XSYSignRsp) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{1}
}

func (x *XSYSignRsp) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYSignRsp) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

//*
//  request: verify sign and add slave admin
type XSYAddAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYAddAdminReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp     `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYAddAdmin) Reset() {
	*x = XSYAddAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddAdmin) ProtoMessage() {}

func (x *XSYAddAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddAdmin.ProtoReflect.Descriptor instead.
func (*XSYAddAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{2}
}

func (x *XSYAddAdmin) GetData() *XSYAddAdminReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYAddAdmin) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// request: add master admin
type XSYAddMasterAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"` //master address
}

func (x *XSYAddMasterAdmin) Reset() {
	*x = XSYAddMasterAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddMasterAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddMasterAdmin) ProtoMessage() {}

func (x *XSYAddMasterAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddMasterAdmin.ProtoReflect.Descriptor instead.
func (*XSYAddMasterAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{3}
}

func (x *XSYAddMasterAdmin) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

//*
// request: delete slave admin request
// send message to master
type XSYDeleteAdminReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
}

func (x *XSYDeleteAdminReq) Reset() {
	*x = XSYDeleteAdminReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteAdminReq) ProtoMessage() {}

func (x *XSYDeleteAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteAdminReq.ProtoReflect.Descriptor instead.
func (*XSYDeleteAdminReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{4}
}

func (x *XSYDeleteAdminReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

//*
// Structure used for deleting administrator
type XSYDeleteAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYDeleteAdminReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp        `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYDeleteAdmin) Reset() {
	*x = XSYDeleteAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteAdmin) ProtoMessage() {}

func (x *XSYDeleteAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteAdmin.ProtoReflect.Descriptor instead.
func (*XSYDeleteAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{5}
}

func (x *XSYDeleteAdmin) GetData() *XSYDeleteAdminReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYDeleteAdmin) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// request: update slave admin request
// send message to master
type XSYUpdateAdminReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Amount  *uint32 `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
	Version *uint32 `protobuf:"varint,3,req,name=version" json:"version,omitempty"` //update version
}

func (x *XSYUpdateAdminReq) Reset() {
	*x = XSYUpdateAdminReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateAdminReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateAdminReq) ProtoMessage() {}

func (x *XSYUpdateAdminReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateAdminReq.ProtoReflect.Descriptor instead.
func (*XSYUpdateAdminReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{6}
}

func (x *XSYUpdateAdminReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYUpdateAdminReq) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *XSYUpdateAdminReq) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

//*
// Structure used for modifing administrator
type XSYUpdateAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYUpdateAdminReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp        `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYUpdateAdmin) Reset() {
	*x = XSYUpdateAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateAdmin) ProtoMessage() {}

func (x *XSYUpdateAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateAdmin.ProtoReflect.Descriptor instead.
func (*XSYUpdateAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{7}
}

func (x *XSYUpdateAdmin) GetData() *XSYUpdateAdminReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYUpdateAdmin) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// Get admin info
type XSYGetAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
}

func (x *XSYGetAdmin) Reset() {
	*x = XSYGetAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetAdmin) ProtoMessage() {}

func (x *XSYGetAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetAdmin.ProtoReflect.Descriptor instead.
func (*XSYGetAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{8}
}

func (x *XSYGetAdmin) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

//*
// Admin info
type XSYAdmin struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Amount   *uint32 `protobuf:"varint,2,req,name=amount" json:"amount,omitempty"`
	IsMaster *bool   `protobuf:"varint,3,req,name=is_master,json=isMaster" json:"is_master,omitempty"`
	Version  *uint32 `protobuf:"varint,4,opt,name=version" json:"version,omitempty"`
}

func (x *XSYAdmin) Reset() {
	*x = XSYAdmin{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAdmin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAdmin) ProtoMessage() {}

func (x *XSYAdmin) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAdmin.ProtoReflect.Descriptor instead.
func (*XSYAdmin) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{9}
}

func (x *XSYAdmin) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYAdmin) GetAmount() uint32 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *XSYAdmin) GetIsMaster() bool {
	if x != nil && x.IsMaster != nil {
		return *x.IsMaster
	}
	return false
}

func (x *XSYAdmin) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

//*
// Request: Ask for device get administrator list
type XSYGetAdminList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *XSYGetAdminList) Reset() {
	*x = XSYGetAdminList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetAdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetAdminList) ProtoMessage() {}

func (x *XSYGetAdminList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetAdminList.ProtoReflect.Descriptor instead.
func (*XSYGetAdminList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{10}
}

//*
// Response: Structure representing xsyadministrator list
type XSYAdminList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AdminN []*XSYAdmin `protobuf:"bytes,1,rep,name=admin_n,json=adminN" json:"admin_n,omitempty"`
}

func (x *XSYAdminList) Reset() {
	*x = XSYAdminList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAdminList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAdminList) ProtoMessage() {}

func (x *XSYAdminList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAdminList.ProtoReflect.Descriptor instead.
func (*XSYAdminList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{11}
}

func (x *XSYAdminList) GetAdminN() []*XSYAdmin {
	if x != nil {
		return x.AdminN
	}
	return nil
}

//*
// request: add exchange rate
// send message to master
type XSYAddExchangeRateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Exchange []byte  `protobuf:"bytes,2,req,name=exchange" json:"exchange,omitempty"`
}

func (x *XSYAddExchangeRateReq) Reset() {
	*x = XSYAddExchangeRateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddExchangeRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddExchangeRateReq) ProtoMessage() {}

func (x *XSYAddExchangeRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddExchangeRateReq.ProtoReflect.Descriptor instead.
func (*XSYAddExchangeRateReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{12}
}

func (x *XSYAddExchangeRateReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYAddExchangeRateReq) GetExchange() []byte {
	if x != nil {
		return x.Exchange
	}
	return nil
}

//*
// Used for adding exchange rate
type XSYAddExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYAddExchangeRateReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp            `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYAddExchangeRate) Reset() {
	*x = XSYAddExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddExchangeRate) ProtoMessage() {}

func (x *XSYAddExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddExchangeRate.ProtoReflect.Descriptor instead.
func (*XSYAddExchangeRate) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{13}
}

func (x *XSYAddExchangeRate) GetData() *XSYAddExchangeRateReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYAddExchangeRate) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// request: delete exchange rate
// send message to master
type XSYDeleteExchangeRateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
}

func (x *XSYDeleteExchangeRateReq) Reset() {
	*x = XSYDeleteExchangeRateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteExchangeRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteExchangeRateReq) ProtoMessage() {}

func (x *XSYDeleteExchangeRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteExchangeRateReq.ProtoReflect.Descriptor instead.
func (*XSYDeleteExchangeRateReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{14}
}

func (x *XSYDeleteExchangeRateReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

//*
// Structure used for deleting exchange rate
type XSYDeleteExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYDeleteExchangeRateReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp               `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYDeleteExchangeRate) Reset() {
	*x = XSYDeleteExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteExchangeRate) ProtoMessage() {}

func (x *XSYDeleteExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteExchangeRate.ProtoReflect.Descriptor instead.
func (*XSYDeleteExchangeRate) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{15}
}

func (x *XSYDeleteExchangeRate) GetData() *XSYDeleteExchangeRateReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYDeleteExchangeRate) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// request: update exchange rate
// send message to master
type XSYUpdateExchangeRateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Exchange []byte  `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
}

func (x *XSYUpdateExchangeRateReq) Reset() {
	*x = XSYUpdateExchangeRateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateExchangeRateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateExchangeRateReq) ProtoMessage() {}

func (x *XSYUpdateExchangeRateReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateExchangeRateReq.ProtoReflect.Descriptor instead.
func (*XSYUpdateExchangeRateReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{16}
}

func (x *XSYUpdateExchangeRateReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYUpdateExchangeRateReq) GetExchange() []byte {
	if x != nil {
		return x.Exchange
	}
	return nil
}

//*
// Structure used for updating exchange rate
type XSYUpdateExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYUpdateExchangeRateReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp               `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYUpdateExchangeRate) Reset() {
	*x = XSYUpdateExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateExchangeRate) ProtoMessage() {}

func (x *XSYUpdateExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateExchangeRate.ProtoReflect.Descriptor instead.
func (*XSYUpdateExchangeRate) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{17}
}

func (x *XSYUpdateExchangeRate) GetData() *XSYUpdateExchangeRateReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYUpdateExchangeRate) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// Request: Ask for exchange rate of symbol
type XSYGetExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
}

func (x *XSYGetExchangeRate) Reset() {
	*x = XSYGetExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetExchangeRate) ProtoMessage() {}

func (x *XSYGetExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetExchangeRate.ProtoReflect.Descriptor instead.
func (*XSYGetExchangeRate) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{18}
}

func (x *XSYGetExchangeRate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

type XSYExchangeRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol   *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Exchange []byte  `protobuf:"bytes,2,req,name=exchange" json:"exchange,omitempty"`
}

func (x *XSYExchangeRate) Reset() {
	*x = XSYExchangeRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYExchangeRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYExchangeRate) ProtoMessage() {}

func (x *XSYExchangeRate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYExchangeRate.ProtoReflect.Descriptor instead.
func (*XSYExchangeRate) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{19}
}

func (x *XSYExchangeRate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYExchangeRate) GetExchange() []byte {
	if x != nil {
		return x.Exchange
	}
	return nil
}

//*
// Request: Ask for device get exchange rate list
type XSYGetExchangeRateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *XSYGetExchangeRateList) Reset() {
	*x = XSYGetExchangeRateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetExchangeRateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetExchangeRateList) ProtoMessage() {}

func (x *XSYGetExchangeRateList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetExchangeRateList.ProtoReflect.Descriptor instead.
func (*XSYGetExchangeRateList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{20}
}

//*
// Response: Structure representing xsy exchange rate list
type XSYExchangeRateList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExchangeN []*XSYExchangeRate `protobuf:"bytes,1,rep,name=exchange_n,json=exchangeN" json:"exchange_n,omitempty"`
}

func (x *XSYExchangeRateList) Reset() {
	*x = XSYExchangeRateList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYExchangeRateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYExchangeRateList) ProtoMessage() {}

func (x *XSYExchangeRateList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYExchangeRateList.ProtoReflect.Descriptor instead.
func (*XSYExchangeRateList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{21}
}

func (x *XSYExchangeRateList) GetExchangeN() []*XSYExchangeRate {
	if x != nil {
		return x.ExchangeN
	}
	return nil
}

//*
// Request: add dump master sign
// @next XSYSignRsp
type XSYAddDumpAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Address *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
}

func (x *XSYAddDumpAddressReq) Reset() {
	*x = XSYAddDumpAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddDumpAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddDumpAddressReq) ProtoMessage() {}

func (x *XSYAddDumpAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddDumpAddressReq.ProtoReflect.Descriptor instead.
func (*XSYAddDumpAddressReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{22}
}

func (x *XSYAddDumpAddressReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYAddDumpAddressReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

//*
// Request: add dump address
type XSYAddDumpAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYAddDumpAddressReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp           `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYAddDumpAddress) Reset() {
	*x = XSYAddDumpAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYAddDumpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYAddDumpAddress) ProtoMessage() {}

func (x *XSYAddDumpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYAddDumpAddress.ProtoReflect.Descriptor instead.
func (*XSYAddDumpAddress) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{23}
}

func (x *XSYAddDumpAddress) GetData() *XSYAddDumpAddressReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYAddDumpAddress) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// Request: delete dump master sign
// @next： XSYSignRsp
type XSYDeleteDumpAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
}

func (x *XSYDeleteDumpAddressReq) Reset() {
	*x = XSYDeleteDumpAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteDumpAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteDumpAddressReq) ProtoMessage() {}

func (x *XSYDeleteDumpAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteDumpAddressReq.ProtoReflect.Descriptor instead.
func (*XSYDeleteDumpAddressReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{24}
}

func (x *XSYDeleteDumpAddressReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

//*
// Request: delete dump address
type XSYDeleteDumpAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYDeleteDumpAddressReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp              `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYDeleteDumpAddress) Reset() {
	*x = XSYDeleteDumpAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDeleteDumpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDeleteDumpAddress) ProtoMessage() {}

func (x *XSYDeleteDumpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDeleteDumpAddress.ProtoReflect.Descriptor instead.
func (*XSYDeleteDumpAddress) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{25}
}

func (x *XSYDeleteDumpAddress) GetData() *XSYDeleteDumpAddressReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYDeleteDumpAddress) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// Request: update dump master sign
// @next： XSYSignRsp
type XSYUpdateDumpAddressReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Address *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	Version *uint32 `protobuf:"varint,3,req,name=version" json:"version,omitempty"`
}

func (x *XSYUpdateDumpAddressReq) Reset() {
	*x = XSYUpdateDumpAddressReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateDumpAddressReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateDumpAddressReq) ProtoMessage() {}

func (x *XSYUpdateDumpAddressReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateDumpAddressReq.ProtoReflect.Descriptor instead.
func (*XSYUpdateDumpAddressReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{26}
}

func (x *XSYUpdateDumpAddressReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYUpdateDumpAddressReq) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYUpdateDumpAddressReq) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

//*
// Request: update dump address
type XSYUpdateDumpAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *XSYUpdateDumpAddressReq `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	Sign *XSYSignRsp              `protobuf:"bytes,2,req,name=sign" json:"sign,omitempty"`
}

func (x *XSYUpdateDumpAddress) Reset() {
	*x = XSYUpdateDumpAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[27]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYUpdateDumpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYUpdateDumpAddress) ProtoMessage() {}

func (x *XSYUpdateDumpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[27]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYUpdateDumpAddress.ProtoReflect.Descriptor instead.
func (*XSYUpdateDumpAddress) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{27}
}

func (x *XSYUpdateDumpAddress) GetData() *XSYUpdateDumpAddressReq {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYUpdateDumpAddress) GetSign() *XSYSignRsp {
	if x != nil {
		return x.Sign
	}
	return nil
}

//*
// Request get dump address
type XSYGetDumpAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
}

func (x *XSYGetDumpAddress) Reset() {
	*x = XSYGetDumpAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[28]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetDumpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetDumpAddress) ProtoMessage() {}

func (x *XSYGetDumpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[28]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetDumpAddress.ProtoReflect.Descriptor instead.
func (*XSYGetDumpAddress) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{28}
}

func (x *XSYGetDumpAddress) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

//*
// Response: dump address
type XSYDumpAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol  *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	Address *string `protobuf:"bytes,2,req,name=address" json:"address,omitempty"`
	Version *uint32 `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (x *XSYDumpAddress) Reset() {
	*x = XSYDumpAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[29]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDumpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDumpAddress) ProtoMessage() {}

func (x *XSYDumpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[29]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDumpAddress.ProtoReflect.Descriptor instead.
func (*XSYDumpAddress) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{29}
}

func (x *XSYDumpAddress) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYDumpAddress) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYDumpAddress) GetVersion() uint32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

//*
// Request: list dump address
// @next: XSYDumpAddressList
type XSYGetDumpAddressList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *XSYGetDumpAddressList) Reset() {
	*x = XSYGetDumpAddressList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[30]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYGetDumpAddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYGetDumpAddressList) ProtoMessage() {}

func (x *XSYGetDumpAddressList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[30]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYGetDumpAddressList.ProtoReflect.Descriptor instead.
func (*XSYGetDumpAddressList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{30}
}

type XSYDumpAddressList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DumpAddressN []*XSYDumpAddress `protobuf:"bytes,1,rep,name=dump_address_n,json=dumpAddressN" json:"dump_address_n,omitempty"`
}

func (x *XSYDumpAddressList) Reset() {
	*x = XSYDumpAddressList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[31]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYDumpAddressList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYDumpAddressList) ProtoMessage() {}

func (x *XSYDumpAddressList) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[31]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYDumpAddressList.ProtoReflect.Descriptor instead.
func (*XSYDumpAddressList) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{31}
}

func (x *XSYDumpAddressList) GetDumpAddressN() []*XSYDumpAddress {
	if x != nil {
		return x.DumpAddressN
	}
	return nil
}

//*
// Request: slave admin sign request
// @next XSYSignRsp
// @next Failure
type XSYSignCommonReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Symbol *string `protobuf:"bytes,1,req,name=symbol" json:"symbol,omitempty"`
	To     *string `protobuf:"bytes,2,req,name=to" json:"to,omitempty"` // recipient address
	Amount *string `protobuf:"bytes,3,req,name=amount" json:"amount,omitempty"`
	Random *uint32 `protobuf:"varint,4,req,name=random" json:"random,omitempty"`
}

func (x *XSYSignCommonReq) Reset() {
	*x = XSYSignCommonReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[32]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYSignCommonReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYSignCommonReq) ProtoMessage() {}

func (x *XSYSignCommonReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[32]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYSignCommonReq.ProtoReflect.Descriptor instead.
func (*XSYSignCommonReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{32}
}

func (x *XSYSignCommonReq) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *XSYSignCommonReq) GetTo() string {
	if x != nil && x.To != nil {
		return *x.To
	}
	return ""
}

func (x *XSYSignCommonReq) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *XSYSignCommonReq) GetRandom() uint32 {
	if x != nil && x.Random != nil {
		return *x.Random
	}
	return 0
}

//*
// Response:
type XSYSignCommonRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   *string `protobuf:"bytes,1,req,name=address" json:"address,omitempty"`
	Signature []byte  `protobuf:"bytes,2,req,name=signature" json:"signature,omitempty"` // signature of the message
}

func (x *XSYSignCommonRsp) Reset() {
	*x = XSYSignCommonRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[33]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYSignCommonRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYSignCommonRsp) ProtoMessage() {}

func (x *XSYSignCommonRsp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[33]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYSignCommonRsp.ProtoReflect.Descriptor instead.
func (*XSYSignCommonRsp) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{33}
}

func (x *XSYSignCommonRsp) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *XSYSignCommonRsp) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

//*
// Request: Ask device verify sign  for anticipation
// @next XSYVerifySignRsp
type XSYVerifySignReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignReq *XSYSignCommonReq `protobuf:"bytes,1,req,name=signReq" json:"signReq,omitempty"`
	SignRsp *XSYSignCommonRsp `protobuf:"bytes,2,req,name=signRsp" json:"signRsp,omitempty"`
}

func (x *XSYVerifySignReq) Reset() {
	*x = XSYVerifySignReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[34]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYVerifySignReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYVerifySignReq) ProtoMessage() {}

func (x *XSYVerifySignReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[34]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYVerifySignReq.ProtoReflect.Descriptor instead.
func (*XSYVerifySignReq) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{34}
}

func (x *XSYVerifySignReq) GetSignReq() *XSYSignCommonReq {
	if x != nil {
		return x.SignReq
	}
	return nil
}

func (x *XSYVerifySignReq) GetSignRsp() *XSYSignCommonRsp {
	if x != nil {
		return x.SignRsp
	}
	return nil
}

//*
// Response: verify sign and return value of coinfor anticipation
type XSYVerifySignRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    *string `protobuf:"bytes,1,req,name=amount" json:"amount,omitempty"`                         // value(USDT) of coin
	HasAdmin  *bool   `protobuf:"varint,2,req,name=has_admin,json=hasAdmin" json:"has_admin,omitempty"`    // admin exists
	CurAmount *uint32 `protobuf:"varint,3,req,name=cur_amount,json=curAmount" json:"cur_amount,omitempty"` // current authorized amount
	Error     *string `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`                           //error msg
}

func (x *XSYVerifySignRsp) Reset() {
	*x = XSYVerifySignRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_xsy_proto_msgTypes[35]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYVerifySignRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYVerifySignRsp) ProtoMessage() {}

func (x *XSYVerifySignRsp) ProtoReflect() protoreflect.Message {
	mi := &file_messages_xsy_proto_msgTypes[35]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYVerifySignRsp.ProtoReflect.Descriptor instead.
func (*XSYVerifySignRsp) Descriptor() ([]byte, []int) {
	return file_messages_xsy_proto_rawDescGZIP(), []int{35}
}

func (x *XSYVerifySignRsp) GetAmount() string {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return ""
}

func (x *XSYVerifySignRsp) GetHasAdmin() bool {
	if x != nil && x.HasAdmin != nil {
		return *x.HasAdmin
	}
	return false
}

func (x *XSYVerifySignRsp) GetCurAmount() uint32 {
	if x != nil && x.CurAmount != nil {
		return *x.CurAmount
	}
	return 0
}

func (x *XSYVerifySignRsp) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_messages_xsy_proto protoreflect.FileDescriptor

var file_messages_xsy_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x78, 0x73, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x22, 0x42, 0x0a, 0x0e,
	0x58, 0x53, 0x59, 0x41, 0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x44, 0x0a, 0x0a, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x0b, 0x58, 0x53, 0x59, 0x41, 0x64,
	0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53,
	0x59, 0x41, 0x64, 0x64, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67,
	0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x2d, 0x0a, 0x11, 0x58, 0x53,
	0x59, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2d, 0x0a, 0x11, 0x58, 0x53, 0x59,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x0e, 0x58, 0x53, 0x59,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x3d, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x68, 0x77, 0x2e, 0x74,
	0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78,
	0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72,
	0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73,
	0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69,
	0x67, 0x6e, 0x22, 0x5f, 0x0a, 0x11, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x22, 0x87, 0x01, 0x0a, 0x0e, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x3d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53,
	0x59, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59,
	0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x27, 0x0a,
	0x0b, 0x58, 0x53, 0x59, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x73, 0x0a, 0x08, 0x58, 0x53, 0x59, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x6d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x4d, 0x61, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x11, 0x0a, 0x0f, 0x58,
	0x53, 0x59, 0x47, 0x65, 0x74, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x49,
	0x0a, 0x0c, 0x58, 0x53, 0x59, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39,
	0x0a, 0x07, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x5f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x41, 0x64, 0x6d, 0x69,
	0x6e, 0x52, 0x06, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x4e, 0x22, 0x4b, 0x0a, 0x15, 0x58, 0x53, 0x59,
	0x41, 0x64, 0x64, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x8f, 0x01, 0x0a, 0x12, 0x58, 0x53, 0x59, 0x41, 0x64,
	0x64, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x41, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x68, 0x77,
	0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x41, 0x64, 0x64, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x52,
	0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x32, 0x0a, 0x18, 0x58, 0x53, 0x59, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x95, 0x01, 0x0a,
	0x15, 0x58, 0x53, 0x59, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x44, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53,
	0x59, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e,
	0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x22, 0x4e, 0x0a, 0x18, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x22, 0x95, 0x01, 0x0a, 0x15, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x44,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x68,
	0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x45,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53,
	0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x2c, 0x0a, 0x12,
	0x58, 0x53, 0x59, 0x47, 0x65, 0x74, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61,
	0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x45, 0x0a, 0x0f, 0x58, 0x53,
	0x59, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52, 0x08, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67,
	0x65, 0x22, 0x18, 0x0a, 0x16, 0x58, 0x53, 0x59, 0x47, 0x65, 0x74, 0x45, 0x78, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x5d, 0x0a, 0x13, 0x58,
	0x53, 0x59, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x46, 0x0a, 0x0a, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x6e,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a,
	0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e,
	0x58, 0x53, 0x59, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x61, 0x74, 0x65, 0x52,
	0x09, 0x65, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4e, 0x22, 0x48, 0x0a, 0x14, 0x58, 0x53,
	0x59, 0x41, 0x64, 0x64, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x58, 0x53, 0x59, 0x41, 0x64, 0x64, 0x44,
	0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x40, 0x0a, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72,
	0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73,
	0x79, 0x2e, 0x58, 0x53, 0x59, 0x41, 0x64, 0x64, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e,
	0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e,
	0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04,
	0x73, 0x69, 0x67, 0x6e, 0x22, 0x31, 0x0a, 0x17, 0x58, 0x53, 0x59, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x58, 0x53, 0x59, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x43, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x2f,
	0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20,
	0x02, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59,
	0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x65, 0x0a,
	0x17, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62,
	0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x02, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x93, 0x01, 0x0a, 0x14, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x43, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x68, 0x77,
	0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x75,
	0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x36, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x22, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67,
	0x6e, 0x52, 0x73, 0x70, 0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x22, 0x2b, 0x0a, 0x11, 0x58, 0x53,
	0x59, 0x47, 0x65, 0x74, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x22, 0x5c, 0x0a, 0x0e, 0x58, 0x53, 0x59, 0x44, 0x75,
	0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d,
	0x62, 0x6f, 0x6c, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f,
	0x6c, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x58, 0x53, 0x59, 0x47, 0x65, 0x74, 0x44,
	0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x62,
	0x0a, 0x12, 0x58, 0x53, 0x59, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x4c, 0x0a, 0x0e, 0x64, 0x75, 0x6d, 0x70, 0x5f, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68,
	0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x44, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x0c, 0x64, 0x75, 0x6d, 0x70, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x4e, 0x22, 0x6a, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x02, 0x74, 0x6f, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d,
	0x18, 0x04, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x06, 0x72, 0x61, 0x6e, 0x64, 0x6f, 0x6d, 0x22, 0x4a,
	0x0a, 0x10, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52,
	0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x02, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0c, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x9a, 0x01, 0x0a, 0x10, 0x58,
	0x53, 0x59, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x42, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x02, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53,
	0x59, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x07,
	0x73, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x22, 0x7c, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x61, 0x73, 0x5f, 0x61, 0x64, 0x6d, 0x69, 0x6e,
	0x18, 0x02, 0x20, 0x02, 0x28, 0x08, 0x52, 0x08, 0x68, 0x61, 0x73, 0x41, 0x64, 0x6d, 0x69, 0x6e,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x75, 0x72, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x75, 0x72, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x42, 0x43, 0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x74,
	0x6f, 0x73, 0x68, 0x69, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e,
	0x6c, 0x69, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x10, 0x54, 0x72,
	0x65, 0x7a, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x58, 0x73, 0x79, 0x5a, 0x0a,
	0x2e, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
}

var (
	file_messages_xsy_proto_rawDescOnce sync.Once
	file_messages_xsy_proto_rawDescData = file_messages_xsy_proto_rawDesc
)

func file_messages_xsy_proto_rawDescGZIP() []byte {
	file_messages_xsy_proto_rawDescOnce.Do(func() {
		file_messages_xsy_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_xsy_proto_rawDescData)
	})
	return file_messages_xsy_proto_rawDescData
}

var file_messages_xsy_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_messages_xsy_proto_goTypes = []interface{}{
	(*XSYAddAdminReq)(nil),           // 0: hw.trezor.messages.xsy.XSYAddAdminReq
	(*XSYSignRsp)(nil),               // 1: hw.trezor.messages.xsy.XSYSignRsp
	(*XSYAddAdmin)(nil),              // 2: hw.trezor.messages.xsy.XSYAddAdmin
	(*XSYAddMasterAdmin)(nil),        // 3: hw.trezor.messages.xsy.XSYAddMasterAdmin
	(*XSYDeleteAdminReq)(nil),        // 4: hw.trezor.messages.xsy.XSYDeleteAdminReq
	(*XSYDeleteAdmin)(nil),           // 5: hw.trezor.messages.xsy.XSYDeleteAdmin
	(*XSYUpdateAdminReq)(nil),        // 6: hw.trezor.messages.xsy.XSYUpdateAdminReq
	(*XSYUpdateAdmin)(nil),           // 7: hw.trezor.messages.xsy.XSYUpdateAdmin
	(*XSYGetAdmin)(nil),              // 8: hw.trezor.messages.xsy.XSYGetAdmin
	(*XSYAdmin)(nil),                 // 9: hw.trezor.messages.xsy.XSYAdmin
	(*XSYGetAdminList)(nil),          // 10: hw.trezor.messages.xsy.XSYGetAdminList
	(*XSYAdminList)(nil),             // 11: hw.trezor.messages.xsy.XSYAdminList
	(*XSYAddExchangeRateReq)(nil),    // 12: hw.trezor.messages.xsy.XSYAddExchangeRateReq
	(*XSYAddExchangeRate)(nil),       // 13: hw.trezor.messages.xsy.XSYAddExchangeRate
	(*XSYDeleteExchangeRateReq)(nil), // 14: hw.trezor.messages.xsy.XSYDeleteExchangeRateReq
	(*XSYDeleteExchangeRate)(nil),    // 15: hw.trezor.messages.xsy.XSYDeleteExchangeRate
	(*XSYUpdateExchangeRateReq)(nil), // 16: hw.trezor.messages.xsy.XSYUpdateExchangeRateReq
	(*XSYUpdateExchangeRate)(nil),    // 17: hw.trezor.messages.xsy.XSYUpdateExchangeRate
	(*XSYGetExchangeRate)(nil),       // 18: hw.trezor.messages.xsy.XSYGetExchangeRate
	(*XSYExchangeRate)(nil),          // 19: hw.trezor.messages.xsy.XSYExchangeRate
	(*XSYGetExchangeRateList)(nil),   // 20: hw.trezor.messages.xsy.XSYGetExchangeRateList
	(*XSYExchangeRateList)(nil),      // 21: hw.trezor.messages.xsy.XSYExchangeRateList
	(*XSYAddDumpAddressReq)(nil),     // 22: hw.trezor.messages.xsy.XSYAddDumpAddressReq
	(*XSYAddDumpAddress)(nil),        // 23: hw.trezor.messages.xsy.XSYAddDumpAddress
	(*XSYDeleteDumpAddressReq)(nil),  // 24: hw.trezor.messages.xsy.XSYDeleteDumpAddressReq
	(*XSYDeleteDumpAddress)(nil),     // 25: hw.trezor.messages.xsy.XSYDeleteDumpAddress
	(*XSYUpdateDumpAddressReq)(nil),  // 26: hw.trezor.messages.xsy.XSYUpdateDumpAddressReq
	(*XSYUpdateDumpAddress)(nil),     // 27: hw.trezor.messages.xsy.XSYUpdateDumpAddress
	(*XSYGetDumpAddress)(nil),        // 28: hw.trezor.messages.xsy.XSYGetDumpAddress
	(*XSYDumpAddress)(nil),           // 29: hw.trezor.messages.xsy.XSYDumpAddress
	(*XSYGetDumpAddressList)(nil),    // 30: hw.trezor.messages.xsy.XSYGetDumpAddressList
	(*XSYDumpAddressList)(nil),       // 31: hw.trezor.messages.xsy.XSYDumpAddressList
	(*XSYSignCommonReq)(nil),         // 32: hw.trezor.messages.xsy.XSYSignCommonReq
	(*XSYSignCommonRsp)(nil),         // 33: hw.trezor.messages.xsy.XSYSignCommonRsp
	(*XSYVerifySignReq)(nil),         // 34: hw.trezor.messages.xsy.XSYVerifySignReq
	(*XSYVerifySignRsp)(nil),         // 35: hw.trezor.messages.xsy.XSYVerifySignRsp
}
var file_messages_xsy_proto_depIdxs = []int32{
	0,  // 0: hw.trezor.messages.xsy.XSYAddAdmin.data:type_name -> hw.trezor.messages.xsy.XSYAddAdminReq
	1,  // 1: hw.trezor.messages.xsy.XSYAddAdmin.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	4,  // 2: hw.trezor.messages.xsy.XSYDeleteAdmin.data:type_name -> hw.trezor.messages.xsy.XSYDeleteAdminReq
	1,  // 3: hw.trezor.messages.xsy.XSYDeleteAdmin.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	6,  // 4: hw.trezor.messages.xsy.XSYUpdateAdmin.data:type_name -> hw.trezor.messages.xsy.XSYUpdateAdminReq
	1,  // 5: hw.trezor.messages.xsy.XSYUpdateAdmin.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	9,  // 6: hw.trezor.messages.xsy.XSYAdminList.admin_n:type_name -> hw.trezor.messages.xsy.XSYAdmin
	12, // 7: hw.trezor.messages.xsy.XSYAddExchangeRate.data:type_name -> hw.trezor.messages.xsy.XSYAddExchangeRateReq
	1,  // 8: hw.trezor.messages.xsy.XSYAddExchangeRate.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	14, // 9: hw.trezor.messages.xsy.XSYDeleteExchangeRate.data:type_name -> hw.trezor.messages.xsy.XSYDeleteExchangeRateReq
	1,  // 10: hw.trezor.messages.xsy.XSYDeleteExchangeRate.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	16, // 11: hw.trezor.messages.xsy.XSYUpdateExchangeRate.data:type_name -> hw.trezor.messages.xsy.XSYUpdateExchangeRateReq
	1,  // 12: hw.trezor.messages.xsy.XSYUpdateExchangeRate.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	19, // 13: hw.trezor.messages.xsy.XSYExchangeRateList.exchange_n:type_name -> hw.trezor.messages.xsy.XSYExchangeRate
	22, // 14: hw.trezor.messages.xsy.XSYAddDumpAddress.data:type_name -> hw.trezor.messages.xsy.XSYAddDumpAddressReq
	1,  // 15: hw.trezor.messages.xsy.XSYAddDumpAddress.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	24, // 16: hw.trezor.messages.xsy.XSYDeleteDumpAddress.data:type_name -> hw.trezor.messages.xsy.XSYDeleteDumpAddressReq
	1,  // 17: hw.trezor.messages.xsy.XSYDeleteDumpAddress.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	26, // 18: hw.trezor.messages.xsy.XSYUpdateDumpAddress.data:type_name -> hw.trezor.messages.xsy.XSYUpdateDumpAddressReq
	1,  // 19: hw.trezor.messages.xsy.XSYUpdateDumpAddress.sign:type_name -> hw.trezor.messages.xsy.XSYSignRsp
	29, // 20: hw.trezor.messages.xsy.XSYDumpAddressList.dump_address_n:type_name -> hw.trezor.messages.xsy.XSYDumpAddress
	32, // 21: hw.trezor.messages.xsy.XSYVerifySignReq.signReq:type_name -> hw.trezor.messages.xsy.XSYSignCommonReq
	33, // 22: hw.trezor.messages.xsy.XSYVerifySignReq.signRsp:type_name -> hw.trezor.messages.xsy.XSYSignCommonRsp
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_messages_xsy_proto_init() }
func file_messages_xsy_proto_init() {
	if File_messages_xsy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_xsy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddAdminReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYSignRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddMasterAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteAdminReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateAdminReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAdmin); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetAdminList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAdminList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddExchangeRateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteExchangeRateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateExchangeRateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYExchangeRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetExchangeRateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYExchangeRateList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddDumpAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYAddDumpAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteDumpAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDeleteDumpAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateDumpAddressReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[27].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYUpdateDumpAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[28].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetDumpAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[29].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDumpAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[30].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYGetDumpAddressList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[31].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYDumpAddressList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[32].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYSignCommonReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[33].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYSignCommonRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[34].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYVerifySignReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_xsy_proto_msgTypes[35].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYVerifySignRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_xsy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_xsy_proto_goTypes,
		DependencyIndexes: file_messages_xsy_proto_depIdxs,
		MessageInfos:      file_messages_xsy_proto_msgTypes,
	}.Build()
	File_messages_xsy_proto = out.File
	file_messages_xsy_proto_rawDesc = nil
	file_messages_xsy_proto_goTypes = nil
	file_messages_xsy_proto_depIdxs = nil
}
