// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.6.1
// source: messages-tron.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//*
// Request: Ask device for Tron address corresponding to address_n path
// @start
// @next TronAddress
// @next Failure
type XSYTronGetAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressN    []uint32 `protobuf:"varint,1,rep,packed,name=address_n,json=addressN,proto3" json:"address_n,omitempty"`   // BIP-32 path to derive the key from master node
	ShowDisplay bool     `protobuf:"varint,2,opt,name=show_display,json=showDisplay,proto3" json:"show_display,omitempty"` // Optionally show on display before sending the result
}

func (x *XSYTronGetAddress) Reset() {
	*x = XSYTronGetAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronGetAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronGetAddress) ProtoMessage() {}

func (x *XSYTronGetAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronGetAddress.ProtoReflect.Descriptor instead.
func (*XSYTronGetAddress) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{0}
}

func (x *XSYTronGetAddress) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *XSYTronGetAddress) GetShowDisplay() bool {
	if x != nil {
		return x.ShowDisplay
	}
	return false
}

//*
// Response: Contains Tron address derived from device private seed
// @end
type XSYTronAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"` // Tron address (base58)
}

func (x *XSYTronAddress) Reset() {
	*x = XSYTronAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronAddress) ProtoMessage() {}

func (x *XSYTronAddress) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronAddress.ProtoReflect.Descriptor instead.
func (*XSYTronAddress) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{1}
}

func (x *XSYTronAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

//*
// Request: Ask device to sign message
// @start
// @next TronMessageSignature
// @next Failure
type XSYTronSignMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressN []uint32 `protobuf:"varint,1,rep,packed,name=address_n,json=addressN,proto3" json:"address_n,omitempty"` // BIP-32 path to derive the key from master node
	Message  []byte   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                           // message to be signed
}

func (x *XSYTronSignMessage) Reset() {
	*x = XSYTronSignMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronSignMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronSignMessage) ProtoMessage() {}

func (x *XSYTronSignMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronSignMessage.ProtoReflect.Descriptor instead.
func (*XSYTronSignMessage) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{2}
}

func (x *XSYTronSignMessage) GetAddressN() []uint32 {
	if x != nil {
		return x.AddressN
	}
	return nil
}

func (x *XSYTronSignMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

//*
// Response: Signed message
// @end
type XSYTronMessageSignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // signature of the message
	Address   string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`     // address used to sign the message
}

func (x *XSYTronMessageSignature) Reset() {
	*x = XSYTronMessageSignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronMessageSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronMessageSignature) ProtoMessage() {}

func (x *XSYTronMessageSignature) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronMessageSignature.ProtoReflect.Descriptor instead.
func (*XSYTronMessageSignature) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{3}
}

func (x *XSYTronMessageSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *XSYTronMessageSignature) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

//------------------------------------------------------------------------
type XSYTronAuthority struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account        *XSYTronAuthority_XSYTronAccountId `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	PermissionName []byte                             `protobuf:"bytes,2,opt,name=permission_name,json=permissionName,proto3" json:"permission_name,omitempty"`
}

func (x *XSYTronAuthority) Reset() {
	*x = XSYTronAuthority{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronAuthority) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronAuthority) ProtoMessage() {}

func (x *XSYTronAuthority) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronAuthority.ProtoReflect.Descriptor instead.
func (*XSYTronAuthority) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{4}
}

func (x *XSYTronAuthority) GetAccount() *XSYTronAuthority_XSYTronAccountId {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *XSYTronAuthority) GetPermissionName() []byte {
	if x != nil {
		return x.PermissionName
	}
	return nil
}

// type = 1
type XSYTransferContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ToAddress    []byte `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Amount       int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *XSYTransferContract) Reset() {
	*x = XSYTransferContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTransferContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTransferContract) ProtoMessage() {}

func (x *XSYTransferContract) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTransferContract.ProtoReflect.Descriptor instead.
func (*XSYTransferContract) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{5}
}

func (x *XSYTransferContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *XSYTransferContract) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}

func (x *XSYTransferContract) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// type = 31
type XSYTriggerSmartContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerAddress    []byte `protobuf:"bytes,1,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	ContractAddress []byte `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	CallValue       int64  `protobuf:"varint,3,opt,name=call_value,json=callValue,proto3" json:"call_value,omitempty"`
	Data            []byte `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	CallTokenValue  int64  `protobuf:"varint,5,opt,name=call_token_value,json=callTokenValue,proto3" json:"call_token_value,omitempty"`
	TokenId         int64  `protobuf:"varint,6,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *XSYTriggerSmartContract) Reset() {
	*x = XSYTriggerSmartContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTriggerSmartContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTriggerSmartContract) ProtoMessage() {}

func (x *XSYTriggerSmartContract) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTriggerSmartContract.ProtoReflect.Descriptor instead.
func (*XSYTriggerSmartContract) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{6}
}

func (x *XSYTriggerSmartContract) GetOwnerAddress() []byte {
	if x != nil {
		return x.OwnerAddress
	}
	return nil
}

func (x *XSYTriggerSmartContract) GetContractAddress() []byte {
	if x != nil {
		return x.ContractAddress
	}
	return nil
}

func (x *XSYTriggerSmartContract) GetCallValue() int64 {
	if x != nil {
		return x.CallValue
	}
	return 0
}

func (x *XSYTriggerSmartContract) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *XSYTriggerSmartContract) GetCallTokenValue() int64 {
	if x != nil {
		return x.CallTokenValue
	}
	return 0
}

func (x *XSYTriggerSmartContract) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type XSYTronContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type         uint32 `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Parameter    []byte `protobuf:"bytes,2,opt,name=parameter,proto3" json:"parameter,omitempty"` // type = 1/31
	Provider     []byte `protobuf:"bytes,3,opt,name=provider,proto3" json:"provider,omitempty"`
	ContractName []byte `protobuf:"bytes,4,opt,name=ContractName,proto3" json:"ContractName,omitempty"`
}

func (x *XSYTronContract) Reset() {
	*x = XSYTronContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronContract) ProtoMessage() {}

func (x *XSYTronContract) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronContract.ProtoReflect.Descriptor instead.
func (*XSYTronContract) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{7}
}

func (x *XSYTronContract) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *XSYTronContract) GetParameter() []byte {
	if x != nil {
		return x.Parameter
	}
	return nil
}

func (x *XSYTronContract) GetProvider() []byte {
	if x != nil {
		return x.Provider
	}
	return nil
}

func (x *XSYTronContract) GetContractName() []byte {
	if x != nil {
		return x.ContractName
	}
	return nil
}

//*
// Request: xsy tron sign tx request
type XSYTronSignTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RefBlockBytes []byte              `protobuf:"bytes,1,opt,name=ref_block_bytes,json=refBlockBytes,proto3" json:"ref_block_bytes,omitempty"`
	RefBlockNum   int64               `protobuf:"varint,3,opt,name=ref_block_num,json=refBlockNum,proto3" json:"ref_block_num,omitempty"`
	RefBlockHash  []byte              `protobuf:"bytes,4,opt,name=ref_block_hash,json=refBlockHash,proto3" json:"ref_block_hash,omitempty"`
	Expiration    int64               `protobuf:"varint,8,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Auths         []*XSYTronAuthority `protobuf:"bytes,9,rep,name=auths,proto3" json:"auths,omitempty"`
	Contract      []*XSYTronContract  `protobuf:"bytes,11,rep,name=contract,proto3" json:"contract,omitempty"`
	Scripts       []byte              `protobuf:"bytes,12,opt,name=scripts,proto3" json:"scripts,omitempty"`
	Timestamp     int64               `protobuf:"varint,14,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FeeLimit      int64               `protobuf:"varint,18,opt,name=fee_limit,json=feeLimit,proto3" json:"fee_limit,omitempty"`
}

func (x *XSYTronSignTx) Reset() {
	*x = XSYTronSignTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronSignTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronSignTx) ProtoMessage() {}

func (x *XSYTronSignTx) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronSignTx.ProtoReflect.Descriptor instead.
func (*XSYTronSignTx) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{8}
}

func (x *XSYTronSignTx) GetRefBlockBytes() []byte {
	if x != nil {
		return x.RefBlockBytes
	}
	return nil
}

func (x *XSYTronSignTx) GetRefBlockNum() int64 {
	if x != nil {
		return x.RefBlockNum
	}
	return 0
}

func (x *XSYTronSignTx) GetRefBlockHash() []byte {
	if x != nil {
		return x.RefBlockHash
	}
	return nil
}

func (x *XSYTronSignTx) GetExpiration() int64 {
	if x != nil {
		return x.Expiration
	}
	return 0
}

func (x *XSYTronSignTx) GetAuths() []*XSYTronAuthority {
	if x != nil {
		return x.Auths
	}
	return nil
}

func (x *XSYTronSignTx) GetContract() []*XSYTronContract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *XSYTronSignTx) GetScripts() []byte {
	if x != nil {
		return x.Scripts
	}
	return nil
}

func (x *XSYTronSignTx) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *XSYTronSignTx) GetFeeLimit() int64 {
	if x != nil {
		return x.FeeLimit
	}
	return 0
}

//*
// Request： Ask device to sign tron transaction
// Response：
// @next Failure
type XSYTronSignTxReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignReq     *XSYSignCommonReq `protobuf:"bytes,1,opt,name=signReq,proto3" json:"signReq,omitempty"`
	SignRsp     *XSYSignCommonRsp `protobuf:"bytes,2,opt,name=signRsp,proto3" json:"signRsp,omitempty"`
	AddressFrom []uint32          `protobuf:"varint,3,rep,packed,name=address_from,json=addressFrom,proto3" json:"address_from,omitempty"`
	Data        *XSYTronSignTx    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *XSYTronSignTxReq) Reset() {
	*x = XSYTronSignTxReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronSignTxReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronSignTxReq) ProtoMessage() {}

func (x *XSYTronSignTxReq) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronSignTxReq.ProtoReflect.Descriptor instead.
func (*XSYTronSignTxReq) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{9}
}

func (x *XSYTronSignTxReq) GetSignReq() *XSYSignCommonReq {
	if x != nil {
		return x.SignReq
	}
	return nil
}

func (x *XSYTronSignTxReq) GetSignRsp() *XSYSignCommonRsp {
	if x != nil {
		return x.SignRsp
	}
	return nil
}

func (x *XSYTronSignTxReq) GetAddressFrom() []uint32 {
	if x != nil {
		return x.AddressFrom
	}
	return nil
}

func (x *XSYTronSignTxReq) GetData() *XSYTronSignTx {
	if x != nil {
		return x.Data
	}
	return nil
}

//*
// Requset: xsy tron sum tx
type XSYTronSumSignTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AddressFrom []uint32       `protobuf:"varint,1,rep,packed,name=address_from,json=addressFrom,proto3" json:"address_from,omitempty"`
	AddressTo   []uint32       `protobuf:"varint,2,rep,packed,name=address_to,json=addressTo,proto3" json:"address_to,omitempty"`
	Data        *XSYTronSignTx `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *XSYTronSumSignTx) Reset() {
	*x = XSYTronSumSignTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronSumSignTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronSumSignTx) ProtoMessage() {}

func (x *XSYTronSumSignTx) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronSumSignTx.ProtoReflect.Descriptor instead.
func (*XSYTronSumSignTx) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{10}
}

func (x *XSYTronSumSignTx) GetAddressFrom() []uint32 {
	if x != nil {
		return x.AddressFrom
	}
	return nil
}

func (x *XSYTronSumSignTx) GetAddressTo() []uint32 {
	if x != nil {
		return x.AddressTo
	}
	return nil
}

func (x *XSYTronSumSignTx) GetData() *XSYTronSignTx {
	if x != nil {
		return x.Data
	}
	return nil
}

type XSYTronAuthority_XSYTronAccountId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    []byte `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Address []byte `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *XSYTronAuthority_XSYTronAccountId) Reset() {
	*x = XSYTronAuthority_XSYTronAccountId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_tron_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *XSYTronAuthority_XSYTronAccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XSYTronAuthority_XSYTronAccountId) ProtoMessage() {}

func (x *XSYTronAuthority_XSYTronAccountId) ProtoReflect() protoreflect.Message {
	mi := &file_messages_tron_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XSYTronAuthority_XSYTronAccountId.ProtoReflect.Descriptor instead.
func (*XSYTronAuthority_XSYTronAccountId) Descriptor() ([]byte, []int) {
	return file_messages_tron_proto_rawDescGZIP(), []int{4, 0}
}

func (x *XSYTronAuthority_XSYTronAccountId) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *XSYTronAuthority_XSYTronAccountId) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_messages_tron_proto protoreflect.FileDescriptor

var file_messages_tron_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x74, 0x72, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x1a, 0x12,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2d, 0x78, 0x73, 0x79, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x53, 0x0a, 0x11, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x47, 0x65, 0x74,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x4e, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x64, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x73, 0x68, 0x6f, 0x77,
	0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x22, 0x2a, 0x0a, 0x0e, 0x58, 0x53, 0x59, 0x54, 0x72,
	0x6f, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0x4b, 0x0a, 0x12, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x5f, 0x6e, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x08, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x4e, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x51, 0x0a, 0x17, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0xd3, 0x01, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x54, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x3a, 0x2e, 0x68, 0x77, 0x2e, 0x74,
	0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74,
	0x72, 0x6f, 0x6e, 0x2e, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x49, 0x64, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27,
	0x0a, 0x0f, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x40, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x54, 0x72,
	0x6f, 0x6e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x71, 0x0a, 0x13, 0x58, 0x53, 0x59,
	0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x74, 0x6f, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xe1, 0x01, 0x0a,
	0x17, 0x58, 0x53, 0x59, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x53, 0x6d, 0x61, 0x72, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x77, 0x6e, 0x65,
	0x72, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x61, 0x6c, 0x6c,
	0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x61,
	0x6c, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x28, 0x0a, 0x10, 0x63,
	0x61, 0x6c, 0x6c, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x61, 0x6c, 0x6c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69,
	0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x22, 0x83, 0x01, 0x0a, 0x0f, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x70, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64,
	0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xfd, 0x02, 0x0a, 0x0d, 0x58, 0x53, 0x59, 0x54, 0x72,
	0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x12, 0x26, 0x0a, 0x0f, 0x72, 0x65, 0x66, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x0d, 0x72, 0x65, 0x66, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6e, 0x75,
	0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x66, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x72, 0x65,
	0x66, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3f, 0x0a, 0x05, 0x61, 0x75,
	0x74, 0x68, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x68, 0x77, 0x2e, 0x74,
	0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74,
	0x72, 0x6f, 0x6e, 0x2e, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x05, 0x61, 0x75, 0x74, 0x68, 0x73, 0x12, 0x44, 0x0a, 0x08, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x28, 0x2e,
	0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x43,
	0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x18, 0x0c, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x65, 0x65,
	0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x12, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x65,
	0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0xf9, 0x01, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x54, 0x72,
	0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x52, 0x65, 0x71, 0x12, 0x42, 0x0a, 0x07, 0x73,
	0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x68,
	0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67, 0x6e, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x12,
	0x42, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x73, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x28, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x78, 0x73, 0x79, 0x2e, 0x58, 0x53, 0x59, 0x53, 0x69, 0x67,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x73, 0x70, 0x52, 0x07, 0x73, 0x69, 0x67, 0x6e,
	0x52, 0x73, 0x70, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x66,
	0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x6f, 0x6e, 0x2e, 0x58,
	0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x90, 0x01, 0x0a, 0x10, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x53, 0x75,
	0x6d, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x5f, 0x66, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0b, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x5f, 0x74, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x09,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x12, 0x3a, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x68, 0x77, 0x2e, 0x74, 0x72, 0x65,
	0x7a, 0x6f, 0x72, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x74, 0x72, 0x6f,
	0x6e, 0x2e, 0x58, 0x53, 0x59, 0x54, 0x72, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x78, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x44, 0x0a, 0x23, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x61, 0x74,
	0x6f, 0x73, 0x68, 0x69, 0x6c, 0x61, 0x62, 0x73, 0x2e, 0x74, 0x72, 0x65, 0x7a, 0x6f, 0x72, 0x2e,
	0x6c, 0x69, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x42, 0x11, 0x54, 0x72,
	0x65, 0x7a, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x72, 0x6f, 0x6e, 0x5a,
	0x0a, 0x2e, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_messages_tron_proto_rawDescOnce sync.Once
	file_messages_tron_proto_rawDescData = file_messages_tron_proto_rawDesc
)

func file_messages_tron_proto_rawDescGZIP() []byte {
	file_messages_tron_proto_rawDescOnce.Do(func() {
		file_messages_tron_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_tron_proto_rawDescData)
	})
	return file_messages_tron_proto_rawDescData
}

var file_messages_tron_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_messages_tron_proto_goTypes = []interface{}{
	(*XSYTronGetAddress)(nil),                 // 0: hw.trezor.messages.tron.XSYTronGetAddress
	(*XSYTronAddress)(nil),                    // 1: hw.trezor.messages.tron.XSYTronAddress
	(*XSYTronSignMessage)(nil),                // 2: hw.trezor.messages.tron.XSYTronSignMessage
	(*XSYTronMessageSignature)(nil),           // 3: hw.trezor.messages.tron.XSYTronMessageSignature
	(*XSYTronAuthority)(nil),                  // 4: hw.trezor.messages.tron.XSYTronAuthority
	(*XSYTransferContract)(nil),               // 5: hw.trezor.messages.tron.XSYTransferContract
	(*XSYTriggerSmartContract)(nil),           // 6: hw.trezor.messages.tron.XSYTriggerSmartContract
	(*XSYTronContract)(nil),                   // 7: hw.trezor.messages.tron.XSYTronContract
	(*XSYTronSignTx)(nil),                     // 8: hw.trezor.messages.tron.XSYTronSignTx
	(*XSYTronSignTxReq)(nil),                  // 9: hw.trezor.messages.tron.XSYTronSignTxReq
	(*XSYTronSumSignTx)(nil),                  // 10: hw.trezor.messages.tron.XSYTronSumSignTx
	(*XSYTronAuthority_XSYTronAccountId)(nil), // 11: hw.trezor.messages.tron.XSYTronAuthority.XSYTronAccountId
	(*XSYSignCommonReq)(nil),                  // 12: hw.trezor.messages.xsy.XSYSignCommonReq
	(*XSYSignCommonRsp)(nil),                  // 13: hw.trezor.messages.xsy.XSYSignCommonRsp
}
var file_messages_tron_proto_depIdxs = []int32{
	11, // 0: hw.trezor.messages.tron.XSYTronAuthority.account:type_name -> hw.trezor.messages.tron.XSYTronAuthority.XSYTronAccountId
	4,  // 1: hw.trezor.messages.tron.XSYTronSignTx.auths:type_name -> hw.trezor.messages.tron.XSYTronAuthority
	7,  // 2: hw.trezor.messages.tron.XSYTronSignTx.contract:type_name -> hw.trezor.messages.tron.XSYTronContract
	12, // 3: hw.trezor.messages.tron.XSYTronSignTxReq.signReq:type_name -> hw.trezor.messages.xsy.XSYSignCommonReq
	13, // 4: hw.trezor.messages.tron.XSYTronSignTxReq.signRsp:type_name -> hw.trezor.messages.xsy.XSYSignCommonRsp
	8,  // 5: hw.trezor.messages.tron.XSYTronSignTxReq.data:type_name -> hw.trezor.messages.tron.XSYTronSignTx
	8,  // 6: hw.trezor.messages.tron.XSYTronSumSignTx.data:type_name -> hw.trezor.messages.tron.XSYTronSignTx
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_messages_tron_proto_init() }
func file_messages_tron_proto_init() {
	if File_messages_tron_proto != nil {
		return
	}
	file_messages_xsy_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_messages_tron_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronGetAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronSignMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronMessageSignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronAuthority); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTransferContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTriggerSmartContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronSignTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronSignTxReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronSumSignTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_tron_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*XSYTronAuthority_XSYTronAccountId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_tron_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_tron_proto_goTypes,
		DependencyIndexes: file_messages_tron_proto_depIdxs,
		MessageInfos:      file_messages_tron_proto_msgTypes,
	}.Build()
	File_messages_tron_proto = out.File
	file_messages_tron_proto_rawDesc = nil
	file_messages_tron_proto_goTypes = nil
	file_messages_tron_proto_depIdxs = nil
}
